name: ros_nodes
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  xmlrpc_server:
    git: git://github.com/sashiri/xmlrpc_server.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0